M48
; DRILL file {KiCad 7.0.10} date Fri Jan 19 17:17:20 2024
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-01-19T17:17:20+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.200
%
G90
G05
T1
X64.139Y-14.848
X64.139Y-17.348
X69.139Y-22.348
X74.139Y-14.848
X74.139Y-17.348
M30
